# Generated by Django 5.1.5 on 2025-02-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
    ]
