# Generated by Django 5.1.5 on 2025-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=20)),
                ('country_phone_code', models.IntegerField(max_length=10)),
            ],
        ),
    ]
