# Generated by Django 5.1.5 on 2025-02-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_country',
        ),
    ]
