# Generated by Django 5.1.5 on 2025-02-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_state')),
            ],
        ),
    ]
