# Generated by Django 5.1.5 on 2025-03-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_tbl_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_skill',
        ),
    ]
