# Generated by Django 5.1.7 on 2025-03-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_tbl_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_skill',
            name='industry',
        ),
        migrations.DeleteModel(
            name='tbl_industry',
        ),
        migrations.DeleteModel(
            name='tbl_skill',
        ),
    ]
