# Generated by Django 5.1.7 on 2025-03-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_remove_tbl_skill_industry_delete_tbl_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_country',
            name='country_phone_code',
            field=models.IntegerField(),
        ),
    ]
