-- These datas are being generated using ChatGpt 4o

USE db;

INSERT INTO user_profiles (profile_usersId, full_name, username, identity, phone, city, bio, degree_type, institution, field_of_study, graduation_month, graduation_year, links) VALUES
(2, 'Akhil', 'akhil', 'Male', '9876543210', 'Kochi', 'Passionate about volunteering for the environment.', 'BCA', 'XYZ College', 'Computer Science', 'May', 2024, 'https://akhil-profile.com'),
(3, 'Arjun', 'arjun', 'Male', '9876543211', 'Trivandrum', 'Experienced organizer of cultural events.', 'BTech', 'ABC University', 'Civil Engineering', 'June', 2023, 'https://arjun-portfolio.com'),
(4, 'Binu', 'binu', 'Male', '9876543212', 'Kollam', 'Works as both volunteer and organizer.', 'BCom', 'DEF College', 'Commerce', 'April', 2024, NULL),
(5, 'Cyril', 'cyril', 'Male', '9876543213', 'Alappuzha', 'Admin managing multiple large-scale events.', 'MCA', 'GHI University', 'Computer Applications', 'July', 2022, 'https://cyril.com'),
(6, 'Deepak', 'deepak', 'Male', '9876543214', 'Thrissur', 'Active volunteer for community development.', 'BCA', 'JKL College', 'Computer Science', 'May', 2024, NULL),
(7, 'Emil', 'emil', 'Male', '9876543215', 'Kannur', 'Focused on volunteering in rural education.', 'BBA', 'MNO College', 'Business Administration', 'April', 2023, NULL),
(8, 'Faisal', 'faisal', 'Male', '9876543216', 'Kozhikode', 'Organizer of technical workshops.', 'MBA', 'PQR University', 'Management', 'August', 2023, 'https://faisal-events.com'),
(9, 'Gokul', 'gokul', 'Male', '9876543217', 'Palakkad', 'Volunteers and organizes health camps.', 'BCA', 'STU College', 'Information Technology', 'June', 2024, NULL),
(10, 'Hari', 'hari', 'Male', '9876543218', 'Malappuram', 'Volunteer for environmental causes.', 'BSc', 'VWX College', 'Botany', 'March', 2023, NULL),
(11, 'Ishaan', 'ishaan', 'Male', '9876543219', 'Kottayam', 'Admin overseeing multiple projects.', 'MTech', 'ABC University', 'Civil Engineering', 'July', 2022, 'https://ishaan.com'),
(12, 'Jay', 'jay', 'Male', '9876543220', 'Trivandrum', 'Organizes tech events for students.', 'BCA', 'XYZ College', 'Information Technology', 'April', 2023, NULL),
(13, 'Kiran', 'kiran', 'Male', '9876543221', 'Kochi', 'Active volunteer in community projects.', 'BSc', 'GHI College', 'Physics', 'May', 2024, NULL),
(14, 'Lal', 'lal', 'Male', '9876543222', 'Thrissur', 'Both a volunteer and organizer of events.', 'BCom', 'JKL College', 'Commerce', 'June', 2023, NULL),
(15, 'Manu', 'manu', 'Male', '9876543223', 'Kollam', 'Dedicated volunteer for health causes.', 'BCA', 'MNO College', 'Computer Science', 'March', 2024, NULL),
(16, 'Nikhil', 'nikhil', 'Male', '9876543224', 'Kozhikode', 'Organizer of tech competitions.', 'BSc', 'XYZ College', 'Physics', 'May', 2024, 'https://nikhil-events.com'),
(17, 'Omar', 'omar', 'Male', '9876543225', 'Kannur', 'Admin managing logistics for events.', 'MBA', 'PQR University', 'Business Administration', 'July', 2023, NULL),
(18, 'Pavan', 'pavan', 'Male', '9876543226', 'Palakkad', 'Volunteer focusing on education.', 'BCA', 'STU College', 'Computer Science', 'June', 2023, NULL),
(19, 'Rajesh', 'rajesh', 'Male', '9876543227', 'Alappuzha', 'Organizer for sports events.', 'BBA', 'ABC University', 'Management', 'April', 2023, NULL),
(20, 'Sahil', 'sahil', 'Male', '9876543228', 'Trivandrum', 'Both a volunteer and organizer.', 'BCom', 'DEF College', 'Commerce', 'May', 2024, NULL),
(21, 'Tinu', 'tinu', 'Male', '9876543229', 'Malappuram', 'Admin overseeing tech workshops.', 'MCA', 'GHI University', 'Information Technology', 'July', 2022, NULL),
(22, 'Unni', 'unni', 'Male', '9876543230', 'Kollam', 'Organizer for social welfare events.', 'BSc', 'JKL College', 'Physics', 'April', 2024, NULL),
(23, 'Vijay', 'vijay', 'Male', '9876543231', 'Kochi', 'Volunteer working in rural development.', 'BBA', 'MNO College', 'Business Administration', 'March', 2023, NULL),
(24, 'Ajith', 'ajith', 'Male', '9876543232', 'Thrissur', 'Both an organizer and volunteer.', 'BCA', 'XYZ College', 'Information Technology', 'May', 2024, NULL),
(25, 'Balan', 'balan', 'Male', '9876543233', 'Kannur', 'Admin focusing on event coordination.', 'MBA', 'PQR University', 'Business Administration', 'July', 2023, 'https://balan-profile.com'),
(26, 'Charan', 'charan', 'Male', '9876543234', 'Kollam', 'Organizer for cultural events.', 'BCom', 'DEF College', 'Commerce', 'April', 2023, NULL),
(27, 'Dileep', 'dileep', 'Male', '9876543235', 'Kozhikode', 'Active volunteer in community work.', 'BCA', 'ABC College', 'Computer Science', 'May', 2024, NULL),
(28, 'Eashan', 'eashan', 'Male', '9876543236', 'Thrissur', 'Both a volunteer and organizer.', 'BSc', 'XYZ College', 'Physics', 'June', 2023, NULL),
(29, 'Firoz', 'firoz', 'Male', '9876543237', 'Palakkad', 'Admin handling event logistics.', 'MBA', 'GHI University', 'Business Administration', 'July', 2023, 'https://firoz-profile.com'),
(30, 'George', 'george', 'Male', '9876543238', 'Kochi', 'Organizer of tech-related events.', 'BCA', 'JKL College', 'Information Technology', 'April', 2024, NULL),
(31, 'Hariharan', 'hariharan', 'Male', '9876543239', 'Kollam', 'Volunteer focusing on health care.', 'BBA', 'MNO College', 'Business Administration', 'March', 2023, NULL),
(32, 'Isac', 'isac', 'Male', '9876543240', 'Kannur', 'Both a volunteer and organizer.', 'BCom', 'ABC College', 'Commerce', 'May', 2024, NULL),
(33, 'Jithu', 'jithu', 'Male', '9876543241', 'Alappuzha', 'Admin handling major event operations.', 'MCA', 'XYZ University', 'Information Technology', 'July', 2022, NULL),
(34, 'Karan', 'karan', 'Male', '9876543242', 'Kochi', 'Organizer of large-scale sports events.', 'BSc', 'GHI University', 'Physics', 'April', 2024, NULL),
(35, 'Lijo', 'lijo', 'Male', '9876543243', 'Palakkad', 'Active volunteer in social causes.', 'BCom', 'JKL College', 'Commerce', 'May', 2023, NULL),
(36, 'Midhun', 'midhun', 'Male', '9876543244', 'Trivandrum', 'Organizer in tech-focused events.', 'BCA', 'DEF College', 'Information Technology', 'June', 2024, NULL),
(37, 'Naveen', 'naveen', 'Male', '9876543245', 'Kollam', 'Admin organizing major community events.', 'MBA', 'ABC University', 'Business Administration', 'July', 2023, NULL),
(38, 'Dev', 'dev', 'Male', 'dev@example.com', 'Thrissur', 'Active volunteer in environmental campaigns.', 'BSc', 'XYZ College', 'Botany', 'May', 2024, NULL),
(39, 'Prakash', 'prakash', 'Male', '9876543246', 'Palakkad', 'Both a volunteer and organizer.', 'BCA', 'PQR College', 'Information Technology', 'June', 2023, NULL),
(40, 'Ravi', 'ravi', 'Male', '9876543247', 'Alappuzha', 'Organizer of cultural programs.', 'BCom', 'DEF College', 'Commerce', 'April', 2023, NULL),
(41, 'Sandeep', 'sandeep', 'Male', '9876543248', 'Kozhikode', 'Volunteer for environmental preservation.', 'BSc', 'ABC College', 'Botany', 'March', 2023, NULL),
(42, 'Tarun', 'tarun', 'Male', '9876543249', 'Kannur', 'Admin managing educational events.', 'MCA', 'XYZ University', 'Computer Applications', 'July', 2022, NULL),
(43, 'Umesh', 'umesh', 'Male', '9876543250', 'Kochi', 'Organizer of social welfare programs.', 'BBA', 'DEF University', 'Management', 'May', 2024, 'https://umesh.com'),
(44, 'Vimal', 'vimal', 'Male', '9876543251', 'Kollam', 'Both a volunteer and organizer.', 'BCA', 'GHI College', 'Information Technology', 'June', 2024, NULL),
(45, 'Ajay', 'ajay', 'Male', '9876543252', 'Palakkad', 'Organizer of tech conferences.', 'MBA', 'JKL University', 'Management', 'July', 2023, NULL),
(46, 'Bharath', 'bharath', 'Male', '9876543253', 'Trivandrum', 'Active volunteer for social causes.', 'BSc', 'XYZ University', 'Physics', 'April', 2024, NULL),
(47, 'Chetan', 'chetan', 'Male', '9876543254', 'Alappuzha', 'Organizer of health care events.', 'BCom', 'DEF College', 'Commerce', 'May', 2023, NULL),
(48, 'Anoop', 'anoop', 'Male', '9876543255', 'Kozhikode', 'Both a volunteer and organizer.', 'BBA', 'GHI College', 'Business Administration', 'March', 2023, NULL),
(49, 'Ebin', 'ebin', 'Male', '9876543256', 'Thrissur', 'Admin managing tech events.', 'MCA', 'JKL University', 'Information Technology', 'July', 2022, NULL),
(50, 'Farhan', 'farhan', 'Male', '9876543257', 'Kochi', 'Organizer of cultural events.', 'BCom', 'DEF University', 'Commerce', 'April', 2023, 'https://farhan-dev.com');
