INSERT INTO Events (organizer_id, event_name, event_description, event_datetime, event_location, event_thumbnail, created_at) VALUES
(1, 'Summer Music Festival', 'Join us for a day of live music performances!', '2024-07-15 14:00:00', 'Central Park', 'https://example.com/summer_fest.jpg', NOW()),
(1, 'Tech Conference 2024', 'Explore the latest in technology and innovation', '2024-09-20 09:00:00', 'Convention Center', 'https://example.com/tech_conf.jpg', NOW()),
(2, 'Charity Run', 'Annual 5K run to raise funds for local charities', '2024-05-01 08:00:00', 'City Marathon Course', 'https://example.com/charity_run.jpg', NOW()),
(2, 'Art Exhibition Opening', 'Featuring works from emerging local artists', '2024-06-10 18:00:00', 'Downtown Gallery', 'https://example.com/art_exhibit.jpg', NOW()),
(3, 'Food Truck Festival', 'Taste cuisines from around the world', '2024-08-05 11:00:00', 'Riverside Park', 'https://example.com/food_truck.jpg', NOW()),
(3, 'Business Networking Mixer', 'Connect with professionals in your industry', '2024-04-12 19:00:00', 'Grand Hotel Ballroom', 'https://example.com/networking.jpg', NOW()),
(4, 'Yoga in the Park', 'Free community yoga session for all levels', '2024-06-01 07:00:00', 'Sunset Park', 'https://example.com/yoga_park.jpg', NOW()),
(4, 'Film Festival', 'Showcasing independent films from around the globe', '2024-10-15 12:00:00', 'City Cinema', 'https://example.com/film_fest.jpg', NOW()),
(5, 'Science Fair', 'Annual event for students to showcase their projects', '2024-05-20 10:00:00', 'Community Center', 'https://example.com/science_fair.jpg', NOW()),
(5, 'Book Club Meeting', 'Discussion on this months selected novel', '2024-04-05 18:30:00', 'Public Library', 'https://example.com/book_club.jpg', NOW()),
(1, 'Career Fair', 'Connect with potential employers in various industries', '2024-09-01 10:00:00', 'University Campus', 'https://example.com/career_fair.jpg', NOW()),
(2, 'Holiday Craft Market', 'Shop handmade gifts from local artisans', '2024-12-10 11:00:00', 'Community Hall', 'https://example.com/craft_market.jpg', NOW()),
(3, 'Photography Workshop', 'Learn techniques from professional photographers', '2024-07-22 13:00:00', 'Art Studio', 'https://example.com/photo_workshop.jpg', NOW()),
(4, 'Startup Pitch Competition', 'Entrepreneurs compete for funding opportunities', '2024-11-05 15:00:00', 'Innovation Hub', 'https://example.com/startup_pitch.jpg', NOW()),
(5, 'Farmers Market', 'Fresh local produce and artisanal goods', '2024-06-08 08:00:00', 'Town Square', 'https://example.com/farmers_market.jpg', NOW()),
(1, 'Comedy Night', 'Laugh out loud with top stand-up comedians', '2024-08-18 20:00:00', 'Laugh Factory', 'https://example.com/comedy_night.jpg', NOW()),
(2, 'Kids Science Camp', 'Week-long summer camp for young scientists', '2024-07-10 09:00:00', 'Science Center', 'https://example.com/science_camp.jpg', NOW()),
(3, 'Wine Tasting Evening', 'Sample wines from local vineyards', '2024-09-15 19:00:00', 'Vineyard Restaurant', 'https://example.com/wine_tasting.jpg', NOW()),
(4, 'Antique Car Show', 'Display of classic and vintage automobiles', '2024-05-30 10:00:00', 'Fairgrounds', 'https://example.com/car_show.jpg', NOW()),
(5, 'Hackathon', '24-hour coding competition for developers', '2024-10-01 18:00:00', 'Tech Incubator', 'https://example.com/hackathon.jpg', NOW());
