# Generated by Django 5.1.5 on 2025-02-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_guest',
        ),
    ]
