# Generated by Django 5.1.7 on 2025-03-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_volexp',
        ),
    ]
