# Generated by Django 5.1.7 on 2025-03-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_remove_tbl_user_user_volexp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
