# Generated by Django 5.1.5 on 2025-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0006_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_username', models.CharField(max_length=50, unique=True)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_address', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=128)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('user_photo', models.FileField(blank=True, null=True, upload_to='Assets/File/user/')),
                ('identity', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('degree_type', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation_month', models.IntegerField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('official_address', models.CharField(blank=True, max_length=200, null=True)),
                ('official_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_basic_profile_complete', models.BooleanField(default=False)),
                ('is_volunteer_profile_complete', models.BooleanField(default=False)),
                ('is_organizer_profile_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
