# Generated by Django 5.1.7 on 2025-04-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_initial'),
        ('User', '0011_remove_tbl_event_event_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
