# Generated by Django 5.1.5 on 2025-03-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_user',
            old_name='bio',
            new_name='user_bio',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='city',
            new_name='user_city',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='country',
            new_name='user_degree_type',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='emergency_name',
            new_name='user_emergency_name',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='emergency_phone',
            new_name='user_emergency_phone',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='field_of_study',
            new_name='user_field_of_study',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='graduation_month',
            new_name='user_graduation_month',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='graduation_year',
            new_name='user_graduation_year',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='industry',
            new_name='user_industry',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='job_title',
            new_name='user_institution',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='links',
            new_name='user_links',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='location',
            new_name='user_location',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='official_contact_number',
            new_name='user_official_contact_number',
        ),
        migrations.RenameField(
            model_name='tbl_user',
            old_name='organization_name',
            new_name='user_organization_name',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='degree_type',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='official_address',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='state',
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='user_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='user_job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='user_official_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='user_type',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('organizer', 'Organizer'), ('both', 'Both')], default='volunteer', max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(blank=True, null=True, upload_to='assets/File/user/'),
        ),
    ]
