# Generated by Django 5.1.5 on 2025-03-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_rename_bio_tbl_user_user_bio_and_more'),
        ('User', '0016_remove_tbl_feedback_user_id_delete_tbl_complaint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
