# Generated by Django 5.1.5 on 2025-03-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0009_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_username', models.CharField(max_length=50, unique=True)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_contact', models.CharField(max_length=10)),
                ('user_address', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=128)),
                ('user_city', models.CharField(blank=True, max_length=50, null=True)),
                ('user_photo', models.FileField(blank=True, null=True, upload_to='assets/File/user/')),
                ('user_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('user_bio', models.TextField(blank=True, null=True)),
                ('user_links', models.TextField(blank=True, null=True)),
                ('user_degree_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('user_field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('user_graduation_month', models.IntegerField(blank=True, null=True)),
                ('user_graduation_year', models.IntegerField(blank=True, null=True)),
                ('user_emergency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_emergency_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('user_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('user_location', models.CharField(blank=True, max_length=100, null=True)),
                ('user_official_address', models.CharField(blank=True, max_length=200, null=True)),
                ('user_official_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_basic_profile_complete', models.BooleanField(default=False)),
                ('is_volunteer_profile_complete', models.BooleanField(default=False)),
                ('is_organizer_profile_complete', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('organizer', 'Organizer'), ('both', 'Both')], default='volunteer', max_length=10)),
            ],
        ),
    ]
