# Generated by Django 5.1.5 on 2025-03-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_initial'),
        ('User', '0018_remove_tbl_feedback_user_id_delete_tbl_complaint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
