# Generated by Django 5.1.7 on 2025-03-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
