# Generated by Django 5.1.7 on 2025-03-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_initial'),
        ('User', '0026_remove_tbl_feedback_user_id_delete_tbl_complaint_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
