# Generated by Django 5.1.7 on 2025-03-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_event',
        ),
    ]
