# Generated by Django 5.1.7 on 2025-03-22 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_alter_tbl_country_country_phone_code'),
        ('Guest', '0001_initial'),
        ('User', '0002_delete_tbl_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('event_content', models.CharField(max_length=30)),
                ('event_datetime', models.DateTimeField()),
                ('event_file', models.FileField(upload_to='Assets/Files/User')),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_venue', models.CharField(max_length=30)),
                ('event_stipend', models.CharField(max_length=30)),
                ('event_status', models.IntegerField(default=0)),
                ('event_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_city')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
