# Generated by Django 5.1.7 on 2025-03-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_request',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_event',
        ),
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
