# Generated by Django 5.1.7 on 2025-03-29 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_alter_tbl_country_country_phone_code'),
        ('Guest', '0001_initial'),
        ('User', '0005_remove_tbl_request_event_remove_tbl_request_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('event_content', models.CharField(max_length=30)),
                ('event_datetime', models.DateTimeField()),
                ('event_file', models.FileField(upload_to='Assets/Files/User')),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_venue', models.CharField(max_length=30)),
                ('event_stipend', models.CharField(max_length=30)),
                ('event_status', models.IntegerField(default=0)),
                ('volunteer_slots', models.PositiveIntegerField(default=1)),
                ('application_deadline', models.DateTimeField()),
                ('visibility', models.IntegerField(default=1)),
                ('event_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_city')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_industry')),
                ('required_skills', models.ManyToManyField(to='User.tbl_skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='User.tbl_event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to='Guest.tbl_user')),
            ],
        ),
    ]
