# Generated by Django 5.1.5 on 2025-02-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
