# Generated by Django 5.1.7 on 2025-03-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_event_tbl_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_event',
            name='event_city',
        ),
        migrations.RemoveField(
            model_name='tbl_event',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='tbl_event',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='tbl_event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_industry',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_skill',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_event',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
        migrations.DeleteModel(
            name='tbl_industry',
        ),
        migrations.DeleteModel(
            name='tbl_skill',
        ),
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
