# Generated by Django 5.1.7 on 2025-03-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0021_alter_tbl_country_country_phone_code'),
        ('Guest', '0006_initial'),
        ('User', '0007_remove_tbl_event_event_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=30)),
                ('complaint_content', models.CharField(max_length=1000)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=1000)),
                ('complaint_reply_date', models.DateField(null=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(max_length=1000)),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
                ('event_content', models.CharField(max_length=30)),
                ('event_datetime', models.DateTimeField()),
                ('event_file', models.FileField(upload_to='Assets/Files/User')),
                ('event_created_at', models.DateTimeField(auto_now_add=True)),
                ('event_venue', models.CharField(max_length=30)),
                ('event_stipend', models.CharField(max_length=30)),
                ('event_status', models.IntegerField(default=0)),
                ('volunteer_slots', models.PositiveIntegerField(default=1)),
                ('application_deadline', models.DateTimeField()),
                ('visibility', models.IntegerField(default=1)),
                ('event_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_industry')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='User.tbl_event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='User.tbl_industry')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_event',
            name='required_skills',
            field=models.ManyToManyField(to='User.tbl_skill'),
        ),
    ]
