# Generated by Django 5.1.7 on 2025-04-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_request',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tbl_industry',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_skill',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_event',
        ),
        migrations.DeleteModel(
            name='tbl_industry',
        ),
        migrations.DeleteModel(
            name='tbl_skill',
        ),
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
