# Generated by Django 5.1.7 on 2025-04-18 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_tbl_industry_tbl_event_tbl_request_tbl_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_event',
            name='event_city',
        ),
        migrations.RemoveField(
            model_name='tbl_event',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='tbl_event',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='tbl_event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_event',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
