# Generated by Django 5.1.5 on 2025-02-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply_date',
            field=models.DateField(null=True),
        ),
    ]
