# Generated by Django 5.1.5 on 2025-02-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_tbl_complaint_complaint_reply_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
