# Generated by Django 5.1.5 on 2025-03-01 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
