# Generated by Django 5.1.7 on 2025-03-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
