# Generated by Django 5.1.7 on 2025-03-21 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_remove_tbl_skill_industry_delete_tbl_industry_and_more'),
        ('Guest', '0020_initial'),
        ('User', '0028_tbl_industry_tbl_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_content', models.CharField(max_length=2000)),
                ('event_time', models.TimeField()),
                ('event_file', models.FileField(upload_to='assets/File/user')),
                ('event_address', models.CharField(max_length=200)),
                ('event_stipend', models.CharField(max_length=200)),
                ('event_status', models.IntegerField(default=0)),
                ('event_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_city')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
