# Generated by Django 5.1.7 on 2025-03-21 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0020_initial'),
        ('User', '0029_tbl_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.TimeField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='User.tbl_event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_requests', to='Guest.tbl_user')),
            ],
        ),
    ]
