# Generated by Django 5.1.7 on 2025-03-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_tbl_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
